on:
  push:
    branches: 
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      run: |
          mkdir -p project/
           echo "some jar file" > project/Something.jar
           echo "another jar file" > project/Another.jar
    
    - name: 📂 SFTP uploader
      uses: wangyucode/sftp-upload-action@v1.3.3
      with:
        host: 'access888801288.webspace-data.io'
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        localDir: 'deploy'
        remoteDir: '/clickandbuilds/deploy/'
        exclude: '!Something.jar'
        excludeMode: 'ignore'
